services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /tmp/home-assistant:/config
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Budapest